import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import { RedesignMetricsPage } from "./metrics-page";
const meta = { title: "Redesign/Pages/Metrics/Overview", component: RedesignMetricsPage, args: { initialView: "overview" }, parameters: { layout: "fullscreen" } } satisfies Meta<typeof RedesignMetricsPage>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Normal: Story = {};
export const Loading: Story = { args: { state: "loading" } };
export const Empty: Story = { args: { state: "empty" } };
export const Error: Story = { args: { state: "error" } };
export const Mobile390: Story = { parameters: { viewport: { defaultViewport: "mobile" } } };
